### ISSUE TITLE
Passed local Test in Web - npm ERR! in atom 

### ISSUE THREAD

**Issue by rTfact** [learn-co-curriculum/js-hoisting-readme#16]
1) hoisting "before all" hook:                                                              
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this tes
t.                                                                                            
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)                                 
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:297:18)                            
      at _combinedTickCallback (internal/process/next_tick.js:67:7)                           
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by tsaelatny** [comment]
Did you ever figure out how to fix this issue?
